FIND_PATH(UUDEVIEW_INCLUDE_DIR uudeview.h /usr/include/ /usr/local/include/)

FIND_LIBRARY(UUDEVIEW_LIBRARY NAMES libuu uu PATH /usr/lib /usr/lib64 /usr/local/lib ) 

IF (UUDEVIEW_INCLUDE_DIR)
   MESSAGE(STATUS "Found UUDEVIEW INCLUDE DIR")
ENDIF (UUDEVIEW_INCLUDE_DIR)

IF (UUDEVIEW_LIBRARY)
   MESSAGE(STATUS "Found UUDEVIEW_LIBRARY")
ENDIF (UUDEVIEW_LIBRARY)

IF (UUDEVIEW_INCLUDE_DIR AND UUDEVIEW_LIBRARY)
   SET(UUDEVIEW_FOUND TRUE)
ENDIF (UUDEVIEW_INCLUDE_DIR AND UUDEVIEW_LIBRARY)


IF (UUDEVIEW_FOUND)
   IF (NOT UUDEVIEW_FIND_QUIETLY)
      MESSAGE(STATUS "Found UUDEVIEW: ${UUDEVIEW_LIBRARY}")
   ENDIF (NOT UUDEVIEW_FIND_QUIETLY)
ELSE (UUDEVIEW_FOUND)
   IF (UUDEVIEW_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find UUDEVIEW")
   ENDIF (UUDEVIEW_FIND_REQUIRED)
ENDIF (UUDEVIEW_FOUND)
 
